### ISSUE TITLE
Events close to the exit time of the program don't get written

### ISSUE THREAD

**Issue by psiniemi** [j256/cloudwatch-logback-appender#10]
The appender does not try to flush remaining messages to CloudWatch on stop, so final messages typically don't get written. These messages are specially important in the case of failures that cause an exit or short-lived workloads.

**Comment by j256** [comment]
Huh.  It's supposed to @psiniemi.  In the `stop()` method it interrupts and then joins with the sender thread.  That code is supposed to drain the queue.  Certainly there are race conditions so that the appended may stop _before_ other components that are still logging but in looking at the code I can't see a path where messages queued _before_ the thread is interrupted are lost.

Can you explain the execution path to me more?  Thanks.

**Comment by j256** [comment]
I'm going to close this since no response.  Feel free to reopen.

**Comment by jsyrjala** [comment]
You'll need to have some code that will call the logback's `stop()` method.

See
- https://logback.qos.ch/manual/configuration.html#stopContext
- https://jira.qos.ch/browse/LOGBACK-1090

For example for standalone Java applications to have something like this in `logback.xml`:

```
    <shutdownHook class="ch.qos.logback.core.hook.DelayingShutdownHook"/>
```

Maybe this should be mentioned in README.md?

**Comment by jsyrjala** [comment]
Having said that, it seems that I am also losing last few messages, even though I am using the shutdownHooks etc described above.

I have a standalone Java app, that basically just logs stuff from multiple threads  and then exists (returns from `main()`). The last few messages do not end up into CloudWatch. If I add a 1 minute delay just before exist, everything works.

**Comment by borisbsu** [comment]
Created PR for this issue:
https://github.com/j256/cloudwatch-logback-appender/pull/44

By using shutdown hook we can properly handle writing remaining events into CloudWatch.
